pipeline:
    build:
        image: armhf/ubuntu:latest
        pull: true
        commands:
            - apt-get -y install cmake pip
            - pip install --yes conan
            - mkdir build
            - cd build
            - conan install ..
            - cmake ..
            - make -j2
