pipeline:
    build:
        image: ubuntu:latest
        pull: true
        commands:
            - apt-get -y update
            - apt-get -y install cmake python3-pip
            - pip install --yes conan
            - mkdir build
            - cd build
            - conan install ..
            - cmake ..
            - make
