pipeline:
    build:
        image: conanio/gcc8:latest
        pull: true
        commands:
            - mkdir build
            - cd build
            - conan install ..
            - cmake ..
            - make
