pipeline:
  build:
      image: armv7/armhf-ubuntu
      pull: true
      commands:
          - apt-get install cmake
          - mkdir build
          - cd build
          - cmake ..
          - make -j4
