pipeline:
    build:
        image: armv7/armhf-ubuntu:latest
        pull: true
        commands:
            - apt-get install cmake
            - mkdir build
            - cd build
            - cmake ..
            - make -j4
